# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93e545f8835fe6f7d5e03708447aebc73ec2e2f171604065221636b94c9fe4f70f462e2095728efed73526cd638eeaae9ce746df2ebffee447416d81a9378314

test:
  secret_key_base: 79d35517c325e4837215f94d0676e4c9ecbf5f0e31d8e2ef46d36a13ffb73f88c20d11428e7a6b90871ad2db0aba95b669418ecd1434c397f00cf90691de1a7f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
